name: Feature Request
description: Request a new feature for this SDK?
labels: [ enhancement ]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature request?
      description: |
        Please leave a helpful description of the feature request here.
    validations:
      required: true
  - type: textarea
    id: dotnetVersion
    attributes:
      label: .NET Version
      description: |
        Please, also indicate the application's type where you are expecting to see the new feature (MVC, WebForms, Web API)
        
        ```console
        $ dotnet --version
        # paste output here
        ```
    validations:
      required: true    
  - type: textarea
    id: documentation
    attributes:
      label: Provide a documentation link if applicable
      description: |
        Please provide any links to the documentation that is at
        https://developer.okta.com/. This will help us with this
        feature request.

  - type: textarea
    id: additional
    attributes:
      label: Additional Information?

